"""add approvers and agent api keys

Revision ID: 72e38b54a7c2
Revises: f9e2010028e5
Create Date: 2026-09-29 12:19:44.687695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e38b54a7c2'
down_revision: Union[str, None] = 'f9e2010028e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvers')),
    sa.UniqueConstraint('username', name=op.f('uq_approvers_username'))
    )
    op.add_column('agents', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_agents_api_key_hash'), 'agents', ['api_key_hash'])
    op.create_index('uq_audit_log_one_resolution_per_request', 'audit_log', ['action_request_id'], unique=True, postgresql_where=sa.text("event_type IN ('approved', 'rejected')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_audit_log_one_resolution_per_request', table_name='audit_log', postgresql_where=sa.text("event_type IN ('approved', 'rejected')"))
    op.drop_constraint(op.f('uq_agents_api_key_hash'), 'agents', type_='unique')
    op.drop_column('agents', 'api_key_hash')
    op.drop_table('approvers')
    # ### end Alembic commands ###
