"""add rate_limits

Revision ID: f9e2010028e5
Revises: bcc0d2b2b546
Create Date: 2026-09-25 00:32:17.294062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e2010028e5'
down_revision: Union[str, None] = 'bcc0d2b2b546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_requests > 0', name=op.f('ck_rate_limits_max_requests_positive')),
    sa.CheckConstraint('window_seconds > 0', name=op.f('ck_rate_limits_window_seconds_positive')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_rate_limits_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limits'))
    )
    op.create_index(op.f('ix_rate_limits_action_type'), 'rate_limits', ['action_type'], unique=False)
    op.create_index(op.f('ix_rate_limits_agent_id'), 'rate_limits', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limits_agent_id'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_action_type'), table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
