"""initial schema

Revision ID: bcc0d2b2b546
Revises: 
Create Date: 2026-09-25 00:13:40.376002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Tables that are insert-only by design (ADR-001). Enforced here at the DB
# level so it holds even for connections that bypass the app.
APPEND_ONLY_TABLES = ("audit_log", "action_requests")

REJECT_MUTATION_FN = """
CREATE FUNCTION reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$;
"""


# revision identifiers, used by Alembic.
revision: str = 'bcc0d2b2b546'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('allowed_action_types', postgresql.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('name', name=op.f('uq_agents_name'))
    )
    op.create_table('action_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_action_requests_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_requests'))
    )
    op.create_index(op.f('ix_action_requests_action_type'), 'action_requests', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_requests_agent_id'), 'action_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_action_requests_created_at'), 'action_requests', ['created_at'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.String(length=20), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny', 'needs_approval')", name=op.f('ck_policy_rules_effect_valid')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_policy_rules_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rules'))
    )
    op.create_index(op.f('ix_policy_rules_action_type'), 'policy_rules', ['action_type'], unique=False)
    op.create_index(op.f('ix_policy_rules_agent_id'), 'policy_rules', ['agent_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('action_request_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('allowed', 'denied', 'needs_approval', 'approved', 'rejected', 'executed', 'execution_failed')", name=op.f('ck_audit_log_event_type_valid')),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.id'], name=op.f('fk_audit_log_action_request_id_action_requests')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_audit_log_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action_request_id'), 'audit_log', ['action_request_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action_type'), 'audit_log', ['action_type'], unique=False)
    op.create_index('ix_audit_log_agent_created', 'audit_log', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index('uq_audit_log_one_decision_per_request', 'audit_log', ['action_request_id'], unique=True, postgresql_where=sa.text("event_type IN ('allowed', 'denied', 'needs_approval')"))
    # ### end Alembic commands ###

    op.execute(REJECT_MUTATION_FN)
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_no_update_delete BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation()"
        )


def downgrade() -> None:
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_no_update_delete ON {table}")
    op.execute("DROP FUNCTION reject_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_audit_log_one_decision_per_request', table_name='audit_log', postgresql_where=sa.text("event_type IN ('allowed', 'denied', 'needs_approval')"))
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index('ix_audit_log_agent_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action_request_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_policy_rules_agent_id'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_action_type'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_action_requests_created_at'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_agent_id'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_action_type'), table_name='action_requests')
    op.drop_table('action_requests')
    op.drop_table('agents')
    # ### end Alembic commands ###
